dataset_name: melanoma
base_dataset: melanoma
batch_size: 128
epochs: 10
init_lr: 0.01
warmup_epochs: 0
lr_steps:
  - 5
  - 0.001
weight_decay: 0.001
save_every: 1
train_test_split: False
dataset_classes:
  - name: no-melanoma 
    class_type: head
    old_labels: [1]
  - name: melanoma
    class_type: tail
    old_labels: [0]