dataset_name: petfinder
base_dataset: petfinder
epochs: 30
init_lr: 0.01
warmup_epochs: 0
lr_steps:
  - 15
  - 0.001
  - 20
  - 0.0001
  - 25
  - 0.00001
weight_decay: 0.000001
save_every: 5
dataset_classes:
  - name: cat 
    class_type: head
    old_labels: [0]
  - name: dog
    class_type: tail
    old_labels: [1]